apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "youtrack.fullname" . }}-data-pv
  labels:
    {{- include "youtrack.labels" . | nindent 4 }}
spec:
  resources:
    requests:
      storage: 10Gi
  storageClassName: {{ .Values.volume.storageClass }}
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "youtrack.fullname" . }}-conf-pv
  labels:
    {{- include "youtrack.labels" . | nindent 4 }}
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.volume.storageClass }}
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "youtrack.fullname" . }}-logs-pv
  labels:
    {{- include "youtrack.labels" . | nindent 4 }}
spec:
  resources:
    requests:
      storage: 5Gi
  storageClassName: {{ .Values.volume.storageClass }}
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "youtrack.fullname" . }}-backups-pv
  labels:
    {{- include "youtrack.labels" . | nindent 4 }}
spec:
  resources:
    requests:
      storage: 5Gi
  storageClassName: {{ .Values.volume.storageClass }}
  accessModes:
    - ReadWriteOnce
